### ISSUE TITLE
Please fork properly

### ISSUE THREAD

**Issue by aluaces** [TSUKER/wireguard-install#1]
Hello, in order to modify an existing project, you cannot remove previous copyright notes (see https://gist.github.com/fbaierl/1d740a7925a6e0e608824eb27a429370).

In addition, it is easy for everybody to see your own modifications if you just fork the original project instead of just copying the files and creating a new repository.

Thanks!

**Comment by TSUKER** [comment]
This project was not created by me and got in this form, therefore partner links to data centers are saved.
Added found copyrights, judging by the code - what was found.
If there is more accurate data, please inform.
